### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by GenericConfluent** [GenericConfluent/finescale#14]
## Task
![Screen Shot 2024-03-06 at 10 04 11 AM](https://github.com/GenericConfluent/finescale/assets/36684089/02080477-a60c-4f75-9844-5685e5529613)
(Don't worry about the fact that the Desired courses are at the bottom of the right panel, that an effect from a local change I'm not going to be pushing yet as I work on the `GraphWidget`)
**Spacing and alignment:**
- [ ] Align the two buttons in the top so that they are vertically centered like the text.
- [ ] Add spacing around left and right sides of the text input. (Could do all sides too)
- [ ] Add the same amount of spacing for the desired course list, and then increase it so that the text input is wider than rows for the listed courses.
- [ ] Make the spacing for the desired and required courses equivalent.

**Colour:**
- [ ] Make the background colour of the icon buttons in the top right transparent and make the text the blue colour of the current background.
- [ ] Delete icons should also have a transparent background colour but be a warm colour (red is good), pull it from the pallet.
