### ISSUE TITLE
Create `CourseSet`

### ISSUE THREAD

**Issue by GenericConfluent** [GenericConfluent/finescale#16]
## Motivation
After building up the course graph so that optimal dependencies can be found the next step is collapsing those dependencies and desired courses back down into a list of sets of courses where the dependency requirements are met. 

## Task
- [x] Define `struct CourseSet`
- [x] Define `enum Dependency`
- [x] `CourseGraph::course_dependency(&self, lhs: &CourseId, rhs: &CourseId) -> Dependency`
- [x] `CourseGraph::set_dependency(&self, lhs: CourseSet, rhs: CourseSet) -> Dependency`
- [x] `CourseGraph::swap_course(&self, lhs: &mut CourseSet, rhs: &mut CourseSet, lid: &CourseId, rid: &CourseId) -> anyhow::Error<()>`
- [x] ~`CourseGraph::can_swap_course(&self, lhs: &mut CourseSet, rhs: &mut CourseSet, lid: &CourseId, rid: &CourseId) -> bool`~ (Not actually useful)
- [x] `CourseGraph::swap_set(&self, ordered_sets: &mut Vec<CourseSet>, fst: usize, snd: usize) -> anyhow::Error<()>`
- [x] ~`CourseSet::view(&self) -> Element<_, _, _>`~
- [x] `CourseGraph::build_sets(&self, required: &[NodeIndex]) -> Vec<CourseSet>`
