### ISSUE TITLE
Make `CourseDatabase` more useful

### ISSUE THREAD

**Issue by GenericConfluent** [GenericConfluent/finescale#4]
## Task
Currently `CourseDatabase` has one method implemented on it: `Default::default`. Which is just used for building a sample `CourseDatabase`. In other words, it's useless. Here your job is to make it useful which includes the following:

- [x] ~~Implement `fn ids(&self) -> \\ flexible but ideally iterable`. So that you can see which courses are available.~~ (Not needed when the inner type of `CourseDatabase` is exposed)
- [x] Implement serialization into [Graphviz DOT](https://www.graphviz.org/doc/info/lang.html), feel free to piggyback off of [`petgraph`](https://crates.io/crates/petgraph).
- [x] Implement `fn get(&self, id: &CourseId) -> &Course;` So it's actually possible to retrieve a course.
- [x] Implement deserialization using [`serde`](https://crates.io/crates/serde) and one of it's backends. This somewhat depends on what happens with #3 and the open pull #2. But the scraper is in very early development, far away from needing to be serialized yet. And additionally `serde` is backend agnostic. (Ended up with ron)
- [x] BONUS: Internally `CourseDatabase` is just a `Vec<Course>`. If all we were implementing was `get` and `ids` a `HashMap` would be better suited, except in the future it may be useful to implement a `filter` function to select all the courses that are 400 level, or select all the courses that depend on a course. An in-memory database like [`redis`](https://redis.io/) may be better suited for something like that. Or there may be a better way to store and access stuff. Or may make more sense to store stuff as an actual graph using `petgraph`. This bonus involves figuring out what that is. 

## Motivation
A more concrete `CourseDatabase` would greatly help guide the development of the `GraphWidget` and the course selection algorithm. 

Additionally having the ability to have sample graphs in test files would be nice. And the serialization to graphviz will make it easier to a) inspect the output of the scraper, and b) check that the `GraphWidget` is rendering properly. It also technically makes us able to see the dependency graphs which is a core part of the project.

## Implementation
Build off existing code. Or if you have a better way to store stuff do that instead.

**Comment by GenericConfluent** [comment]
May need to customize the Dot serialization later on, but this is fine for now.
