### ISSUE TITLE
Very basic UI

### ISSUE THREAD

**Issue by GenericConfluent** [GenericConfluent/finescale#8]
## Task
Build the following using [`iced`](https://docs.rs/iced/0.12.1/iced/):
![20240301_08h35m24s_grim](https://github.com/GenericConfluent/finescale/assets/36684089/0bf2b91a-52d4-4348-8954-ca511b001de8)

- [x] Input into the text box should be added to the list of desired classes after an enter.
- [x] The delete icon should remove stuff (kind of obvious)
- [x] All desired classes should be in the required classes _in sorted order_.
- [x] The little icon should be able to handle click events but the event handler can be empty. It'll be used later on to either open the graph as an SVG in-app or in the user's default web browser.

## Motivation
Have a bare UI that can be used to test the key features.

## Implementation
All using the basic widgets that come along with iced. See [iced todos example](https://github.com/iced-rs/iced/tree/af9fb367f361a564aa2a9fc11333816566eb5d55/examples/todos) if you have never used `iced` before, it very similar to the side panel so it should be a good place to start using the `todos` example as a reference.

**Comment by GenericConfluent** [comment]
I was going to start on this, but iced-rs/iced#2297 happens to affect me. I'll be working on #4 instead. I'll push the little I wrote to the repo.

**Comment by GenericConfluent** [comment]
Alignment, spacing and colouration need more work. Otherwise, the skeleton is in place.
